apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    environment: dev
spec:
  template:
    metadata:
      labels:
        environment: dev
    # spec:
    #   containers:
    #     - name: app
    #       image: kp6657/devopsproject:latest
