apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    environment: dev
spec:
  selector:
    environment: dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 6565
      nodePort: 30080
  

