apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-app
    environment: dev
  name: devops-service
  namespace: devops-dev
spec:
  ports:
  - nodePort: 30080
    port: 80
    targetPort: 6565
  selector:
    app: devops-app
    environment: dev
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-app
    environment: dev
  name: devops-app
  namespace: devops-dev
spec:
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
        environment: dev
    spec:
      containers:
      - image: kp6657/devopsproject:latest
        name: app
        ports:
        - containerPort: 6565
