apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: devops-prod
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
images:
- name: docker.io/kp6657/devopsproject
  newTag: "1"
