apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    environment: prod
spec:
  selector:
    environment: prod
  type: NodePort
  ports:
    - port: 80
      targetPort: 6565
      nodePort: 30082
  

