name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker-Credentials

    env:
      IMAGE_NAME: kp6657/devopsproject

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get next semantic version tag
        id: tag
        run: |
          VERSION="1.0.0"
          TAGS=$(curl -s https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags | jq -r '.results[].name')
          MAX_PATCH=0
          for tag in $TAGS; do
            if [[ $tag =~ ^1\.0\.([0-9]+)$ ]]; then
              PATCH=${BASH_REMATCH[1]}
              if (( PATCH > MAX_PATCH )); then
                MAX_PATCH=$PATCH
              fi
            fi
          done
          NEXT_VERSION="1.0.$((MAX_PATCH + 1))"
          echo "tag=$NEXT_VERSION" >> $GITHUB_OUTPUT


      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.tag.outputs.tag }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: 1

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}
