apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-staging-app
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/khushpatel25/DevOpsProject-Manifests
    targetRevision: HEAD
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
