apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-staging-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khushpatel25/DevOpsProject-Manifests
    targetRevision: HEAD
    path: overlays/staging
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
